import { TrendingUp, TrendingDown, AlertCircle, FileText, Copy } from 'lucide-react';
import type { SavingsResult, TimeFrame } from '@/types/ddc';
import { formatCurrency } from '@/lib/ddc/calculator';
import { exportDDCReportToPDF } from '@/lib/ddc/export-ddc-pdf';
import pricingData from '@/data/pricing.json';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';

interface ResultsCardsProps {
  results: SavingsResult;
  timeFrame: TimeFrame;
}

export function ResultsCards({ results, timeFrame }: ResultsCardsProps) {
  const memberships = [
    {
      tier: 'basic',
      data: results.basic,
      info: pricingData.memberships.basic,
      color: 'blue',
    },
    {
      tier: 'premium',
      data: results.premium,
      info: pricingData.memberships.premium,
      color: 'purple',
    },
    {
      tier: 'pro',
      data: results.pro,
      info: pricingData.memberships.pro,
      color: 'green',
    },
  ];

  // Export to PDF
  const exportToPDF = () => {
    exportDDCReportToPDF(results, timeFrame);
    toast.success('Opening PDF report...');
  };

  // Copy client-friendly summary to clipboard
  const copySummary = () => {
    // Find best tier
    const tiers = [
      { name: 'Basic', savings: results.basic.netSavings, data: results.basic, price: pricingData.memberships.basic.price },
      { name: 'Premium', savings: results.premium.netSavings, data: results.premium, price: pricingData.memberships.premium.price },
      { name: 'Pro', savings: results.pro.netSavings, data: results.pro, price: pricingData.memberships.pro.price },
    ];
    const bestTier = tiers.sort((a, b) => b.savings - a.savings)[0];

    // Calculate savings over time
    const oneYearSavings = bestTier.data.netSavings / timeFrame;
    const fiveYearSavings = oneYearSavings * 5;
    const tenYearSavings = oneYearSavings * 10;

    const summary = `🎯 DOMAIN DISCOUNT CLUB SAVINGS ANALYSIS

📊 YOUR PORTFOLIO:
• ${results.supportedDomains} domains analyzed
• Analysis period: ${timeFrame} year${timeFrame > 1 ? 's' : ''}

💰 RECOMMENDED TIER: ${bestTier.name.toUpperCase()}
• Membership cost: ${formatCurrency(bestTier.price)}/year
• Your net savings: ${formatCurrency(bestTier.savings)}

📈 SAVINGS OVER TIME:
• 1 Year:  ${formatCurrency(oneYearSavings)}
• 5 Years: ${formatCurrency(fiveYearSavings)}
• 10 Years: ${formatCurrency(tenYearSavings)}

${bestTier.savings > 0 ? `⚠️ MONEY LEFT ON THE TABLE: ${formatCurrency(bestTier.savings)}

By not joining the Domain Discount Club, you're leaving ${formatCurrency(bestTier.savings)} in savings on the table!` : '⚠️ Note: You need more domains to make the membership cost-effective.'}

✅ WHY JOIN?
• Automatic renewal discounts on 500+ extensions
• Savings apply year after year
• No coupon codes needed
• Set it and forget it

📝 Note: DDC pricing applies to renewals only. New registrations use promotional pricing, with member discounts starting at first renewal.

---
Generated by HostingInfo Domain Calculator
${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;

    navigator.clipboard.writeText(summary);
    toast.success('Client summary copied to clipboard!');
  };

  return (
    <div className="space-y-6">
      {/* Summary */}
      <div className="bg-card rounded-lg shadow-lg p-6 border border-border">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-bold text-foreground">
            Savings Comparison - {timeFrame} Year{timeFrame !== 1 ? 's' : ''}
          </h2>
          <div className="flex gap-2">
            <Button onClick={copySummary} variant="outline" size="sm">
              <Copy className="w-4 h-4 mr-2" />
              Copy Summary
            </Button>
            <Button onClick={exportToPDF} variant="default" size="sm">
              <FileText className="w-4 h-4 mr-2" />
              Export PDF Proposal
            </Button>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
          <div>
            <span className="text-muted-foreground">Total Domains:</span>
            <span className="ml-2 font-semibold text-foreground">
              {results.totalDomains}
            </span>
          </div>
          <div>
            <span className="text-muted-foreground">Supported:</span>
            <span className="ml-2 font-semibold text-green-500">
              {results.supportedDomains}
            </span>
          </div>
          {results.unsupportedDomains > 0 && (
            <div>
              <span className="text-muted-foreground">Unsupported:</span>
              <span className="ml-2 font-semibold text-yellow-500">
                {results.unsupportedDomains}
              </span>
            </div>
          )}
        </div>
      </div>

      {/* Membership Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {memberships.map(({ tier, data, info }) => {
          const isPositive = data.netSavings > 0;
          const bgColor = isPositive
            ? 'bg-gradient-to-br from-green-500/10 to-green-500/5'
            : 'bg-gradient-to-br from-red-500/10 to-red-500/5';
          const borderColor = isPositive ? 'border-green-500/30' : 'border-red-500/30';

          return (
            <div
              key={tier}
              className={`${bgColor} border-2 ${borderColor} rounded-lg p-6 space-y-4`}
            >
              {/* Header */}
              <div className="border-b border-border pb-4">
                <h3 className="text-xl font-bold text-foreground">{info.name}</h3>
                <p className="text-sm text-muted-foreground mt-1">{info.description}</p>
                <p className="text-lg font-semibold text-foreground mt-2">
                  {formatCurrency(info.price)}/year
                </p>
              </div>

              {/* Savings */}
              <div className="space-y-3">
                <div>
                  <div className="text-sm text-muted-foreground">List Price</div>
                  <div className="text-xl font-bold text-foreground">
                    {formatCurrency(data.totalListPrice)}
                  </div>
                </div>

                <div>
                  <div className="text-sm text-muted-foreground">Member Price</div>
                  <div className="text-xl font-bold text-foreground">
                    {formatCurrency(data.totalMemberPrice)}
                  </div>
                </div>

                <div className="border-t border-border pt-3">
                  <div className="text-sm text-muted-foreground">Gross Savings</div>
                  <div className="text-lg font-semibold text-green-500">
                    {formatCurrency(data.grossSavings)}
                  </div>
                  <div className="text-xs text-muted-foreground mt-1">
                    {((data.grossSavings / data.totalListPrice) * 100).toFixed(1)}% saved
                  </div>
                </div>

                <div>
                  <div className="text-sm text-muted-foreground">Membership Cost</div>
                  <div className="text-lg font-semibold text-red-500">
                    -{formatCurrency(data.membershipCost)}
                  </div>
                  <div className="text-xs text-muted-foreground mt-1">
                    {formatCurrency(info.price)}/year × {timeFrame}
                  </div>
                </div>

                <div className="border-t-2 border-border pt-3">
                  <div className="flex items-center justify-between">
                    <div className="text-sm font-medium text-foreground">Net Savings</div>
                    {isPositive ? (
                      <TrendingUp className="w-5 h-5 text-green-500" />
                    ) : (
                      <TrendingDown className="w-5 h-5 text-red-500" />
                    )}
                  </div>
                  <div
                    className={`text-2xl font-bold ${
                      isPositive ? 'text-green-500' : 'text-red-500'
                    }`}
                  >
                    {formatCurrency(data.netSavings)}
                  </div>
                </div>
              </div>

              {/* Status */}
              {!isPositive && (
                <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-3 flex items-start gap-2">
                  <AlertCircle className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
                  <p className="text-sm text-foreground">
                    Not worth it yet. Need{' '}
                    <strong>
                      {Math.ceil(
                        (data.membershipCost - data.grossSavings) /
                          (data.totalListPrice / results.supportedDomains / timeFrame -
                            data.totalMemberPrice / results.supportedDomains / timeFrame)
                      )}
                    </strong>{' '}
                    more domains to break even.
                  </p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
